#!/bin/bash

source "$HOME/.i3/i3blocks.colors"

bat_path="/sys/class/power_supply/BAT0/"
label=""
color=""

if [ -d $bat_path ]; then
	cap="$(cat $bat_path/capacity)"
	sts="$(cat $bat_path/status)"
	
	if [ $cap -gt 100 ]; then
		cap=100
	fi
	if [ $sts == "Charging" -o $sts == "Full" ]; then
		label=""
	fi

	label="$label$cap%"
	
	if   [ $cap -lt 10 ]; then
		color=$color_err
	elif [ $cap -lt 20 ]; then
		color=$color_warn
	else
		color=$color_good
	fi

	echo "<span foreground='$color'>$label</span>"
fi

	
		
