#!/bin/bash

source "$HOME/.i3/i3blocks.colors"
device=$(ls /sys/class/net | grep -v 'lo')
ip=$(ip addr show $device | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')

if [ -z $ip ]; then
	printf "<span foreground='$color_dis'>down</span>"
else
	printf "<span foreground='$color_good'>$ip</span>"
fi
