#!/bin/bash

config_dir="$HOME/.config/i3blocks_page_monitor"

if ! [ -d config_dir ]; then
	mkdir -p $config_dir
fi

URL="$config_dir/page_monitor.url"
old="$config_dir/.pgmon.old"
new="$config_dir/.pgmon.new"
flg="$config_dir/.pgmon.flg"
state=NOURL

if [ -f $URL ]; then
	url="$(cat $URL)"
	mv $new $old 
	curl $url -L -s > $new
	if ! [ -z "$(diff $new $old)" ]; then
		touch $flg
	fi

	if [ -f $flg ]; then
		state="CHG"
	else
		state="MON"
	fi
fi

print_label() {

label=""
color="#FFFFFF"

case $state in

NOURL	) return "" ;;

CHG	) color="#2D882D"
       	  label="Changed";;

MON	) color="#DCA700";;
esac

printf "<span foreground='$color'>   $label </span>"
}

clear_flag() {
    rm -rf $flg
}

case $BLOCK_BUTTON in
    1) 	firefox -new-tab $url 
	clear_flag
	print_label;;

    3) 	clear_flag
	print_label;;

    *) 	print_label;;
esac 
