#!/bin/bash 

source "$HOME/.i3/i3blocks.colors"

fetch() {
declare -i ID
ID=`xinput list | grep -Eo 'TouchPad\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`
declare -i STATE
return `xinput list-props $ID | grep "Device Enabled"| awk '{print $4}'`
}

toggle() {
fetch
if [ $? -eq 1 ]
then
    xinput disable $ID
else
    xinput enable $ID
fi
}

fetch
if [ $? -eq 1 ];then 
    Label="<span foreground='$color_good'> ON</span>"
else
    Label="<span foreground='$color_dis'> OFF</span>"
fi 

echo $Label

case $BLOCK_BUTTON in
    3) toggle | echo "$Label";;
    *) echo "$Label" ;;
esac

