#!/bin/bash 

toggle() {
declare -i ID
ID=`xinput list | grep -Eo 'TouchPad\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`
declare -i STATE
STATE=`xinput list-props $ID | grep "Device Enabled"| awk '{print $4}'`
if [ $STATE -eq 1 ]
then
    xinput disable $ID
else
    xinput enable $ID
fi
}

declare -i ID
ID=`xinput list | grep -Eo 'TouchPad\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`
declare -i STATE
STATE=`xinput list-props $ID | grep "Device Enabled"| awk '{print $4}'`

if [ "$STATE" = "1" ];then 
    Label='<span foreground="#2D882D"> ON</span>'
else
    Label='<span foreground="#AA3939"> OFF</span>'
fi 

echo $Label

case $BLOCK_BUTTON in
    3) toggle ;;
    *) echo "$Label" ;;
esac

